// ─── Prebuilt Track Templates ────────────────────────────────────
// Singapore-relevant upskilling roadmaps

import { TrackStep } from '../types';

export interface TrackTemplate {
  id: string;
  title: string;
  industry: string;
  description: string;
  estimatedWeeks: number;
  steps: Omit<TrackStep, 'completed'>[];
}

export const TRACK_TEMPLATES: TrackTemplate[] = [
  {
    id: 'tech-swe',
    title: 'Software Engineering',
    industry: 'tech',
    description: 'From fundamentals to production-ready skills. Covers CS basics, web development, and Singapore-relevant certifications.',
    estimatedWeeks: 24,
    steps: [
      {
        id: 'ts1',
        title: 'CS50: Introduction to Computer Science',
        description: 'Harvard\'s flagship CS course. Build a strong foundation in computational thinking, algorithms, and data structures.',
        type: 'course',
        level: 'beginner',
        provider: 'Harvard / edX',
        url: 'https://cs50.harvard.edu',
        estimatedHours: 80,
        order: 0,
      },
      {
        id: 'ts2',
        title: 'freeCodeCamp: Responsive Web Design',
        description: 'Learn HTML, CSS, and responsive design principles through hands-on projects.',
        type: 'course',
        level: 'beginner',
        provider: 'freeCodeCamp',
        url: 'https://freecodecamp.org',
        estimatedHours: 40,
        order: 1,
      },
      {
        id: 'ts3',
        title: 'Build a Personal Portfolio',
        description: 'Apply what you\'ve learned to build and deploy a personal website.',
        type: 'project',
        level: 'beginner',
        estimatedHours: 15,
        order: 2,
      },
      {
        id: 'ts4',
        title: 'JavaScript & TypeScript Mastery',
        description: 'Deep dive into modern JavaScript and TypeScript. Essential for any web/mobile role.',
        type: 'course',
        level: 'intermediate',
        provider: 'Udemy / Coursera',
        estimatedHours: 60,
        order: 3,
      },
      {
        id: 'ts5',
        title: 'React / React Native Development',
        description: 'Learn component-based architecture, state management, and building production apps.',
        type: 'course',
        level: 'intermediate',
        provider: 'Coursera',
        estimatedHours: 50,
        order: 4,
      },
      {
        id: 'ts6',
        title: 'Full-Stack Project: Task Manager App',
        description: 'Build a full-stack application with authentication, database, and deployment.',
        type: 'project',
        level: 'intermediate',
        estimatedHours: 30,
        order: 5,
      },
      {
        id: 'ts7',
        title: 'SkillsFuture: Certified Full-Stack Developer',
        description: 'SSG-approved certification programme. Eligible for SkillsFuture credits.',
        type: 'certification',
        level: 'intermediate',
        provider: 'SkillsFuture Singapore',
        url: 'https://www.skillsfuture.gov.sg',
        estimatedHours: 120,
        order: 6,
      },
      {
        id: 'ts8',
        title: 'System Design & Architecture',
        description: 'Learn scalable system design patterns used by tech companies in Singapore.',
        type: 'course',
        level: 'advanced',
        provider: 'NUS / Coursera',
        estimatedHours: 40,
        order: 7,
      },
      {
        id: 'ts9',
        title: 'AWS Cloud Practitioner Certification',
        description: 'Cloud fundamentals certification. Highly valued by Singapore employers.',
        type: 'certification',
        level: 'advanced',
        provider: 'AWS',
        url: 'https://aws.amazon.com/certification/',
        estimatedHours: 60,
        order: 8,
      },
      {
        id: 'ts10',
        title: 'Open Source Contribution',
        description: 'Contribute to an open source project. Demonstrates real-world collaboration skills.',
        type: 'milestone',
        level: 'advanced',
        estimatedHours: 20,
        order: 9,
      },
    ],
  },
  {
    id: 'tech-ds',
    title: 'Data Science & Analytics',
    industry: 'tech',
    description: 'Learn data analysis, machine learning, and AI. Includes NTU/NUS courses and SkillsFuture certifications.',
    estimatedWeeks: 28,
    steps: [
      {
        id: 'ds1',
        title: 'Python for Data Science',
        description: 'Learn Python fundamentals with focus on data manipulation using pandas and NumPy.',
        type: 'course',
        level: 'beginner',
        provider: 'Coursera / DataCamp',
        estimatedHours: 40,
        order: 0,
      },
      {
        id: 'ds2',
        title: 'Statistics & Probability Fundamentals',
        description: 'Essential statistical concepts for data analysis and hypothesis testing.',
        type: 'course',
        level: 'beginner',
        provider: 'Khan Academy',
        estimatedHours: 30,
        order: 1,
      },
      {
        id: 'ds3',
        title: 'Exploratory Data Analysis Project',
        description: 'Analyse a real-world Singapore dataset (e.g., HDB resale prices, MOM employment data).',
        type: 'project',
        level: 'beginner',
        estimatedHours: 20,
        order: 2,
      },
      {
        id: 'ds4',
        title: 'SQL & Database Management',
        description: 'Master SQL queries, joins, and database design for analytics.',
        type: 'course',
        level: 'intermediate',
        provider: 'Coursera',
        estimatedHours: 30,
        order: 3,
      },
      {
        id: 'ds5',
        title: 'Machine Learning by Andrew Ng',
        description: 'The gold standard ML course. Learn supervised and unsupervised learning.',
        type: 'course',
        level: 'intermediate',
        provider: 'Stanford / Coursera',
        url: 'https://coursera.org/learn/machine-learning',
        estimatedHours: 60,
        order: 4,
      },
      {
        id: 'ds6',
        title: 'NTU Data Analytics Certificate',
        description: 'NTU\'s professional certification in data analytics. SkillsFuture eligible.',
        type: 'certification',
        level: 'intermediate',
        provider: 'NTU Singapore',
        url: 'https://www.ntu.edu.sg',
        estimatedHours: 100,
        order: 5,
      },
      {
        id: 'ds7',
        title: 'Kaggle Competition Entry',
        description: 'Participate in a Kaggle competition to apply ML skills on real problems.',
        type: 'milestone',
        level: 'intermediate',
        provider: 'Kaggle',
        url: 'https://kaggle.com',
        estimatedHours: 30,
        order: 6,
      },
      {
        id: 'ds8',
        title: 'Deep Learning Specialization',
        description: 'Neural networks, CNNs, RNNs, and transformer architectures.',
        type: 'course',
        level: 'advanced',
        provider: 'Coursera',
        estimatedHours: 80,
        order: 7,
      },
      {
        id: 'ds9',
        title: 'Capstone: End-to-End ML Pipeline',
        description: 'Design, train, deploy, and monitor a machine learning model in production.',
        type: 'project',
        level: 'advanced',
        estimatedHours: 40,
        order: 8,
      },
    ],
  },
  {
    id: 'finance-analyst',
    title: 'Financial Analyst',
    industry: 'finance',
    description: 'Build skills for finance roles in Singapore\'s banking and investment sector. Includes CFA prep and SSG certifications.',
    estimatedWeeks: 32,
    steps: [
      {
        id: 'fa1',
        title: 'Financial Accounting Fundamentals',
        description: 'Understand financial statements, balance sheets, and P&L analysis.',
        type: 'course',
        level: 'beginner',
        provider: 'Coursera',
        estimatedHours: 40,
        order: 0,
      },
      {
        id: 'fa2',
        title: 'Excel for Finance Professionals',
        description: 'Advanced Excel skills: pivot tables, VLOOKUP, financial modelling templates.',
        type: 'course',
        level: 'beginner',
        provider: 'Udemy',
        estimatedHours: 20,
        order: 1,
      },
      {
        id: 'fa3',
        title: 'SkillsFuture: Financial Analysis Certificate',
        description: 'SSG-approved programme covering financial analysis and valuation methods.',
        type: 'certification',
        level: 'beginner',
        provider: 'SkillsFuture Singapore',
        url: 'https://www.skillsfuture.gov.sg',
        estimatedHours: 80,
        order: 2,
      },
      {
        id: 'fa4',
        title: 'Corporate Finance & Valuation',
        description: 'DCF modelling, comparable analysis, and M&A fundamentals.',
        type: 'course',
        level: 'intermediate',
        provider: 'Coursera / Wharton',
        estimatedHours: 50,
        order: 3,
      },
      {
        id: 'fa5',
        title: 'Build a Stock Screening Tool',
        description: 'Create a financial model to screen SGX-listed companies using Python.',
        type: 'project',
        level: 'intermediate',
        estimatedHours: 25,
        order: 4,
      },
      {
        id: 'fa6',
        title: 'CFA Level 1 Preparation',
        description: 'Comprehensive preparation for the CFA Level 1 exam, highly valued in Singapore finance.',
        type: 'certification',
        level: 'advanced',
        provider: 'CFA Institute',
        url: 'https://www.cfainstitute.org',
        estimatedHours: 300,
        order: 5,
      },
      {
        id: 'fa7',
        title: 'Bloomberg Terminal Certification',
        description: 'Learn to navigate Bloomberg Terminal. Essential for sell-side and buy-side roles.',
        type: 'certification',
        level: 'advanced',
        provider: 'Bloomberg',
        estimatedHours: 40,
        order: 6,
      },
    ],
  },
  {
    id: 'public-policy',
    title: 'Public Policy & Governance',
    industry: 'public-sector',
    description: 'Prepare for Singapore public sector careers. Covers policy analysis, governance, and gov.sg programmes.',
    estimatedWeeks: 20,
    steps: [
      {
        id: 'pp1',
        title: 'Introduction to Public Policy',
        description: 'Understand policy cycles, stakeholder analysis, and evidence-based policymaking.',
        type: 'course',
        level: 'beginner',
        provider: 'NUS / Coursera',
        estimatedHours: 30,
        order: 0,
      },
      {
        id: 'pp2',
        title: 'Singapore Governance: A Case Study',
        description: 'Analyse Singapore\'s unique governance model, from housing policy to education reform.',
        type: 'course',
        level: 'beginner',
        provider: 'NUS Lee Kuan Yew School',
        estimatedHours: 25,
        order: 1,
      },
      {
        id: 'pp3',
        title: 'Data Analysis for Policy Research',
        description: 'Learn to use data for policy impact assessment and programme evaluation.',
        type: 'course',
        level: 'intermediate',
        provider: 'Coursera',
        estimatedHours: 40,
        order: 2,
      },
      {
        id: 'pp4',
        title: 'Policy Memo Writing',
        description: 'Write a professional policy memo on a Singapore-relevant issue.',
        type: 'project',
        level: 'intermediate',
        estimatedHours: 15,
        order: 3,
      },
      {
        id: 'pp5',
        title: 'Public Service Leadership Programme',
        description: 'Explore PSC scholarship tracks and management associate programmes.',
        type: 'milestone',
        level: 'advanced',
        provider: 'Public Service Commission',
        url: 'https://www.psc.gov.sg',
        estimatedHours: 20,
        order: 4,
      },
    ],
  },
];

export const INDUSTRIES = [
  { id: 'tech', label: 'Technology', icon: 'code' },
  { id: 'finance', label: 'Finance', icon: 'trending-up' },
  { id: 'public-sector', label: 'Public Sector', icon: 'shield' },
  { id: 'consulting', label: 'Consulting', icon: 'briefcase' },
  { id: 'healthcare', label: 'Healthcare', icon: 'heart' },
  { id: 'education', label: 'Education', icon: 'book-open' },
] as const;

export const STATUS_OPTIONS = [
  { id: 'student', label: 'Student', description: 'Currently studying at a polytechnic, uni, or ITE' },
  { id: 'ns', label: 'National Service', description: 'Serving NS, planning for post-NS career' },
  { id: 'working', label: 'Working Professional', description: 'Currently employed, looking to upskill or pivot' },
] as const;
